name: Deploy Firebase Functions

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
      - '.github/workflows/deploy_backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Add environment configuration
    environment: production
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './functions/package-lock.json'
      
      # Check if required secrets are available
      - name: Check Required Secrets
        run: |
          if [ -z "${{ secrets.FIREBASE_TOKEN }}" ]; then
            echo "Error: FIREBASE_TOKEN is not set"
            exit 1
          fi
          if [ -z "${{ secrets.FIREBASE_PROJECT_ID }}" ]; then
            echo "Error: FIREBASE_PROJECT_ID is not set"
            exit 1
          fi
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Install Functions Dependencies
        working-directory: ./functions
        run: npm ci
      
      - name: Fix Linting Issues
        working-directory: ./functions
        run: |
          echo "Fixing linting issues..."
          npm run lint -- --fix || true
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "style: auto-fix linting issues" || true
      
      - name: Build Functions
        working-directory: ./functions
        run: npm run build
      
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          echo "Deploying to Firebase project: $FIREBASE_PROJECT_ID"
          firebase deploy --only functions --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN --force