name: Deploy Firebase Functions

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
      - '.github/workflows/deploy_backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Add environment configuration
    environment: production
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './functions/package-lock.json'
      
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: functions/node_modules
          key: ${{ runner.os }}-functions-${{ hashFiles('functions/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-functions-
      
      # Check if required secrets are available
      - name: Check Required Secrets
        run: |
          if [ -z "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" ]; then
            echo "Error: GOOGLE_APPLICATION_CREDENTIALS is not set"
            exit 1
          fi
          if [ -z "${{ secrets.FIREBASE_PROJECT_ID }}" ]; then
            echo "Error: FIREBASE_PROJECT_ID is not set"
            exit 1
          fi
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "Error: OPENAI_API_KEY is not set"
            exit 1
          fi
      
      - name: Setup Google Cloud Service Account
        run: |
          # Decode base64 service account JSON and save to file
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 -d > /tmp/service-account.json
          
          # Set environment variable for Google Cloud SDK
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/service-account.json
          
          # Verify the service account file is valid JSON
          if ! jq empty /tmp/service-account.json 2>/dev/null; then
            echo "Error: Invalid service account JSON"
            exit 1
          fi
          
          echo "Service account configured successfully"
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Install Functions Dependencies
        working-directory: ./functions
        run: npm ci
      
      - name: TypeScript Check
        working-directory: ./functions
        run: tsc --noEmit
      
      - name: Build Functions
        working-directory: ./functions
        run: |
          npm run build
          if [ $? -ne 0 ]; then
            echo "Build failed - stopping deployment"
            exit 1
          fi
      
      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/service-account.json
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Deploying to Firebase project: $FIREBASE_PROJECT_ID"
          firebase deploy --only functions --project $FIREBASE_PROJECT_ID --force